export enum Genre{
  AFROBEATS = "AFROBEATS",
  AMAPIANO = "AMAPIANO",
  CLUB = "CLUB",
  DANCEHALL = "DANCEHALL",
  DRILL = "DRILL",
  EDM = "EDM",
  JERSEY = "JERSEY",
  LATIN = "LATIN",
  POP = "POP",
  RNB = "RNB",
  SHATTA = "SHATTA",
  TRAP = "TRAP"
}
